[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xed\0\0\x2\xd3\0\0\0\0\0\0\0\0\0\0\x4\xff\0\0\x3\x1f\0\0\0\0\x2\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x4\xed\0\0\x2\xd3)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4\xee\0\0\x2\xad\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=false
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
initial_setup_completed=true
last_environment=local
version=2

[permissions]
auto_grant\camera=true
auto_grant\microphone=true
auto_grant\screen_contents=true

[privacy]
webrtc_shield=true

[system]
confirm_on_close=false
download_path=/home/dav/pCloudDrive
interface_language=system
notificationCounter=true
quit_in_close=false
spellCheckers=false
start_background=false
start_system=false
theme=dark
tray_icon=true
wayland=true

[website]
open_page=false
